/* Shared module imports */
import { baseEmailStyles, themeStyles, componentStyles, EMAIL_ICONS, generateEmailHeader, generateEmailFooter, EMAIL_CONTENT, COMPANY_INFO } from '@shared/email-templates';

/* Generate 2FA disabled email text content */
export const generateUser2FADisabledText = (
  firstName: string,
  lastName: string,
  email: string,
  roleName: string
): string => {
  return `
    Dear ${firstName} ${lastName},

    Two-Factor Authentication (2FA) has been disabled for your ${COMPANY_INFO.COMPANY_NAME} account.

    Your Account Details:
    • Email: ${email}
    • Role: ${roleName}

    IMPORTANT ACTION REQUIRED:
    Since 2FA has been disabled, you need to manually remove this account from your authenticator app to prevent confusion.

    Steps to Remove from Authenticator App:
    1. Open your authenticator app (Google Authenticator, Microsoft Authenticator, Authy, etc.)
    2. Find the entry for: ${email} (POS SaaS Platform)
    3. Delete/Remove this entry from your authenticator app
    4. The app will stop generating codes for this account

    Why Remove It?
    • The codes generated by your app are no longer valid
    • Keeping the entry may cause confusion during login attempts
    • It's a security best practice to keep your authenticator app clean

    Account Security:
    • Your account is now secured with username/password only
    • You can re-enable 2FA anytime from your account settings
    • Consider using a strong, unique password for enhanced security

    Login URL: ${COMPANY_INFO.LOGIN_URL}

    If you have any questions or did not request this change, please contact our support team immediately:
    • Email: ${COMPANY_INFO.SUPPORT_EMAIL}
    • ${EMAIL_CONTENT.SUPPORT_AVAILABILITY}

    Best regards,
    ${COMPANY_INFO.TEAM_NAME}

    ---
    ${EMAIL_CONTENT.DISCLAIMER}
  `.trim();
}

/* Generate 2FA disabled email HTML content */
export const generateUser2FADisabledHTML = (
  firstName: string,
  lastName: string,
  email: string,
  roleName: string
): string => {
  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>2FA Disabled - ${COMPANY_INFO.COMPANY_NAME}</title>
      <style>
        ${baseEmailStyles}
        ${themeStyles.security}

        .header-icon {
          font-size: 48px;
          margin-bottom: 15px;
        }
        .security-message {
          background: rgba(239, 68, 68, 0.1);
          border: 1px solid #EF4444;
          ${componentStyles.card}
          color: #000000;
          text-align: center;
        }
        .security-message .icon {
          font-size: 24px;
          margin-bottom: 10px;
        }
        .security-message .title {
          font-weight: 700;
          font-size: 18px;
          margin-bottom: 5px;
          color: #000000;
        }
        .account-section {
          background: rgba(0, 255, 65, 0.1);
          border: 2px solid #00FF41;
          ${componentStyles.card}
          text-align: center;
        }
        .account-title {
          font-weight: 700;
          color: #000000;
          margin-bottom: 15px;
          font-size: 18px;
        }
        .account-item {
          margin: 15px 0;
          font-size: 16px;
          color: #000000;
        }
        .account-label {
          font-weight: 600;
          color: #000000;
          display: inline-block;
          width: 120px;
        }
        .account-value {
          ${componentStyles.monospace}
          margin-left: 10px;
          display: inline-block;
        }
        .action-required {
          background: rgba(239, 68, 68, 0.1);
          border: 2px solid #EF4444;
          ${componentStyles.card}
          text-align: center;
          margin: 25px 0;
        }
        .action-title {
          font-weight: 700;
          color: #EF4444;
          margin-bottom: 15px;
          font-size: 18px;
        }
        .removal-steps {
          background: rgba(0, 255, 65, 0.05);
          border: 1px solid rgba(0, 255, 65, 0.3);
          ${componentStyles.card}
          color: #000000;
        }
        .removal-steps .title {
          font-weight: 700;
          margin-bottom: 15px;
          color: #000000;
        }
        .removal-steps ol {
          margin: 10px 0;
          padding-left: 20px;
          text-align: left;
        }
        .removal-steps li {
          margin: 8px 0;
          font-size: 14px;
        }
        .why-section {
          background: rgba(0, 255, 65, 0.05);
          border: 1px solid rgba(0, 255, 65, 0.3);
          ${componentStyles.card}
          color: #000000;
        }
        .why-section .title {
          font-weight: 700;
          margin-bottom: 15px;
          color: #000000;
        }
        .why-section ul {
          margin: 10px 0;
          padding-left: 20px;
          text-align: left;
        }
        .why-section li {
          margin: 8px 0;
          font-size: 14px;
        }
        .login-button {
          ${componentStyles.button}
        }
        .login-button:hover {
          transform: translateY(-3px);
          box-shadow: 0 8px 25px rgba(0, 255, 65, 0.4);
        }
        .button-container {
          text-align: center;
          margin: 35px 0;
        }
        .warning-box {
          background: rgba(239, 68, 68, 0.1);
          border: 1px solid #EF4444;
          ${componentStyles.card}
          color: #000000;
          text-align: center;
        }
        .warning-box .title {
          font-weight: 700;
          font-size: 16px;
          margin-bottom: 10px;
          color: #EF4444;
        }
      </style>
    </head>
    <body>
      <div class="container">
        ${generateEmailHeader('2FA Security Update', EMAIL_ICONS.SECURITY)}

        <div class="content">
          <div class="greeting">Hello ${firstName} ${lastName},</div>

          <div class="security-message">
            <div class="icon">${EMAIL_ICONS.WARNING}</div>
            <div class="title">Two-Factor Authentication Disabled</div>
            <div>2FA has been disabled for your account.</div>
          </div>

          <div class="account-section">
            <div class="account-title">${EMAIL_ICONS.USER} Your Account Details</div>
            <div class="account-item">
              <span class="account-label">Email:</span>
              <span class="account-value">${email}</span>
            </div>
            <div class="account-item">
              <span class="account-label">Role:</span>
              <span style="font-weight: 600; color: #00FF41;">${roleName}</span>
            </div>
          </div>

          <div class="action-required">
            <div class="action-title">${EMAIL_ICONS.ERROR} ACTION REQUIRED</div>
            <div>You need to manually remove this account from your authenticator app.</div>
          </div>

          <div class="removal-steps">
            <div class="title">${EMAIL_ICONS.PROGRESS} Steps to Remove from Authenticator App</div>
            <ol>
              <li>Open your authenticator app (Google Authenticator, Microsoft Authenticator, Authy, etc.)</li>
              <li>Find the entry for: <strong>${email}</strong> (POS SaaS Platform)</li>
              <li>Delete/Remove this entry from your authenticator app</li>
              <li>The app will stop generating codes for this account</li>
            </ol>
          </div>

          <div class="why-section">
            <div class="title">${EMAIL_ICONS.INFO} Why Remove It?</div>
            <ul>
              <li>The codes generated by your app are no longer valid</li>
              <li>Keeping the entry may cause confusion during login attempts</li>
              <li>It's a security best practice to keep your authenticator app clean</li>
            </ul>
          </div>

          <div class="warning-box">
            <div class="title">${EMAIL_ICONS.SECURITY} Security Notice</div>
            <div>
              If you did not request this change, please contact support immediately and change your password.
            </div>
          </div>

          <div class="button-container">
            <a href="${COMPANY_INFO.LOGIN_URL}" class="login-button">Login to ${COMPANY_INFO.COMPANY_NAME}</a>
          </div>

          <div class="message">
            Your account is now secured with username/password only. You can re-enable 2FA anytime from your account settings.
            If you have questions, contact us at ${COMPANY_INFO.SUPPORT_EMAIL}.
          </div>
        </div>

        ${generateEmailFooter()}
      </div>
    </body>
    </html>
  `;
}